### PR TITLE
Feature/global shortcut

### PR DESCRIPTION
**Pull request by simoncollins**
* Got Spotlight working using code from https://github.com/ahkohd/tauri-macos-spotlight-example
* Added licensing and attribution

### CODE REVIEW

**Comment by sammcj** [comment]
woa nice work!

**Review by sammcj — CHANGES_REQUESTED** [review]
disregard this comment

**Review by sammcj — APPROVED** [review]
Tested working!

**Review by Dax911 — COMMENTED** [review]
Clever. Love this. Huge thanks.

**Pull request merged**
